- .circleci/Dockerfile
- .circleci/config.yml
- Dockerfile
- docker-compose.yml
- start.sh
> 52: Enabling Docker Layer Caching

- .circleci/Dockerfile
- Dockerfile
- __tests__/api_docs.test.ts
- __tests__/location_kind_test_data.yml
- __tests__/procedure_move_input.yml
- __tests__/procedures_api.test.ts
- __tests__/test_data_factory.ts
- docker-compose.yml
- package-lock.json
- package.json
- src/api_docs/api_docs_generator.ts
- src/entity/entity_api_impl.ts
- src/entity/entity_api_interface.ts
- src/entity/entity_routes.ts
- src/main.ts
- src/papiea.ts
- src/provider_sdk/typescript_sdk.ts
- src/validator/index.ts
> CRUD Engine: Add Procedures to CRUD for `spec-only` entities

- __tests__/entity_api.test.ts
- __tests__/provider_sdk.test.ts
- examples/typescript/location/provider/provider.ts
- package-lock.json
- package.json
- src/api_docs/api_docs_generator.ts
- src/core.ts
- src/databases/spec_db_mongo.ts
- src/entity/entity_api_impl.ts
- src/entity/entity_routes.ts
- src/provider_sdk/typescript_sdk.ts
- src/provider_sdk/typescript_sdk_interface.ts
> 58_Custom metadata additional info field 

- .circleci/Dockerfile
- docker-compose.yml
> Stat papiea faster from prebuild image

- src/api_docs/api_docs_generator.ts
> Group related routes by kind

- __tests__/entity_api.test.ts
- src/api_docs/api_docs_generator.ts
- src/entity/entity_api_impl.ts
- src/entity/entity_api_interface.ts
- src/entity/entity_routes.ts
> Status of spec-only entities should be equal to the spec

- __tests__/database_mongo.test.ts
- __tests__/entity_api.test.ts
- src/databases/status_db_mongo.ts
- src/entity/entity_api_impl.ts
- src/entity/entity_api_interface.ts
- src/entity/entity_routes.ts
> Return statuses in filter entity response

- __tests__/entity_api.test.ts
- src/databases/spec_db_mongo.ts
- src/databases/status_db_mongo.ts
- src/entity/entity_routes.ts
> Filter entities by status

- __tests__/procedure_geolocation_compute_input.yml
- __tests__/procedures_api.test.ts
- __tests__/test_data_factory.ts
- src/entity/entity_api_impl.ts
- src/entity/entity_api_interface.ts
- src/entity/entity_routes.ts
- src/main.ts
> Create kind level procedures

- __tests__/api_docs.test.ts
- __tests__/database_mongo.test.ts
- __tests__/procedure_sum_input.yml
- __tests__/procedure_sum_output.yml
- __tests__/procedures_api.test.ts
- __tests__/provider_api.test.ts
- __tests__/provider_sdk.test.ts
- __tests__/test_data_factory.ts
- examples/typescript/location/provider/config.ts
- src/databases/provider_db_interface.ts
- src/databases/provider_db_mongo.ts
- src/entity/entity_api_impl.ts
- src/entity/entity_api_interface.ts
- src/entity/entity_routes.ts
- src/main.ts
- src/papiea.ts
- src/provider/provider_api_impl.ts
- src/provider/provider_api_interface.ts
- src/provider_sdk/typescript_sdk.ts
> Added provider level procedure api & tests

- __tests__/api_docs.test.ts
- __tests__/entity_api.test.ts
- __tests__/procedures_api.test.ts
- __tests__/provider_api.test.ts
- __tests__/provider_sdk.test.ts
- src/api_docs/api_docs_generator.ts
- src/databases/provider_db_mongo.ts
- src/entity/entity_api_impl.ts
- src/entity/entity_api_interface.ts
- src/entity/entity_routes.ts
- src/main.ts
- src/provider_sdk/typescript_sdk.ts
- src/provider_sdk/typescript_sdk_context_impl.ts
> Entity routes include version

- package-lock.json
- package.json
- start.sh
resolves https://github.com/nutanix/NuCluster-aaS/issues/299
> Fix papiea mongo dependency

- papiea-core/src/core.ts
- papiea-engine/__tests__/test_data_factory.ts
- papiea-engine/src/api_docs/api_docs_generator.ts
- papiea-engine/src/entity/entity_api_impl.ts
- papiea-sdk/src/provider_sdk/typescript_sdk.ts
> Split entity and kind level procedures

- papiea-engine/src/api_docs/api_docs_generator.ts
> Add distinction between kind and entity procedures

- papiea-client/package-lock.json
- papiea-client/package.json
- papiea-client/src/entity_client.ts
- papiea-core/package-lock.json
- papiea-core/package.json
- papiea-engine/package-lock.json
- papiea-engine/package.json
- papiea-sdk/package-lock.json
- papiea-sdk/package.json
> papiea-client is missing `services` in url

- papiea-client/package-lock.json
- papiea-client/package.json
- papiea-core/package-lock.json
- papiea-core/package.json
- papiea-engine/package-lock.json
- papiea-engine/package.json
- papiea-sdk/package-lock.json
- papiea-sdk/package.json
- papiea-sdk/src/provider_sdk/typescript_sdk_context_impl.ts
- papiea-sdk/src/provider_sdk/typescript_sdk_interface.ts
> update_status to use reference instead of metadata

- papiea-client/package-lock.json
- papiea-client/package.json
- papiea-core/package-lock.json
- papiea-core/package.json
- papiea-engine/package-lock.json
- papiea-engine/package.json
- papiea-sdk/package-lock.json
- papiea-sdk/package.json
- papiea-sdk/src/provider_sdk/typescript_sdk.ts
- papiea-sdk/src/provider_sdk/typescript_sdk_context_impl.ts
- papiea-sdk/src/provider_sdk/typescript_sdk_interface.ts
> Add provider update_status

- papiea-engine/__tests__/provider_sdk.test.ts
- papiea-sdk/package-lock.json
- papiea-sdk/package.json
- papiea-sdk/src/provider_sdk/typescript_sdk.ts
- papiea-sdk/src/provider_sdk/typescript_sdk_validation.ts
> Added validation on the provider side

- papiea-engine/__tests__/api_docs.test.ts
- papiea-engine/__tests__/entity_api_auth.test.ts
- papiea-engine/__tests__/provider_sdk.test.ts
- papiea-engine/__tests__/test_data_factory.ts
- papiea-engine/src/api_docs/api_docs_generator.ts
- papiea-engine/src/entity/entity_api_impl.ts
- papiea-engine/src/provider/provider_api_impl.ts
- papiea-engine/src/utils/utils.ts
- papiea-engine/src/validator/index.ts
- papiea-sdk/src/provider_sdk/typescript_sdk.ts
- papiea-sdk/src/provider_sdk/typescript_sdk_interface.ts
- papiea-sdk/src/provider_sdk/typescript_sdk_utils.ts
- papiea-sdk/src/provider_sdk/typescript_sdk_validation.ts
> Fixed undefined in procedures that didn't specify validation

- papiea-client/package-lock.json
- papiea-client/package.json
- papiea-client/src/entity_client.ts
- papiea-core/package-lock.json
- papiea-core/package.json
- papiea-core/src/core.ts
- papiea-engine/package-lock.json
- papiea-engine/package.json
- papiea-sdk/package-lock.json
- papiea-sdk/package.json
- papiea-sdk/src/provider_sdk/typescript_sdk.ts
> Add entity create function with metadata in client

- papiea-core/package.json
- papiea-core/src/core.ts
- papiea-engine/__tests__/api_docs.test.ts
- papiea-engine/__tests__/auth_user_data.test.ts
- papiea-engine/__tests__/database_mongo.test.ts
- papiea-engine/__tests__/entity_api.test.ts
- papiea-engine/__tests__/entity_api_auth.test.ts
- papiea-engine/__tests__/procedures_api.test.ts
- papiea-engine/__tests__/provider_api.test.ts
- papiea-engine/__tests__/provider_sdk.test.ts
- papiea-engine/package.json
- papiea-engine/src/auth/authn.ts
- papiea-engine/src/auth/authz.ts
- papiea-engine/src/auth/crypto.ts
- papiea-engine/src/auth/oauth2.ts
- papiea-engine/src/databases/mongo.ts
- papiea-engine/src/databases/s2skey_db_interface.ts
- papiea-engine/src/databases/s2skey_db_mongo.ts
- papiea-engine/src/entity/entity_api_impl.ts
- papiea-engine/src/main.ts
- papiea-engine/src/provider/provider_api_impl.ts
- papiea-engine/src/provider/provider_api_interface.ts
- papiea-engine/src/provider/provider_routes.ts
- papiea-sdk/package.json
- papiea-sdk/src/provider_sdk/typescript_sdk.ts
Resolves #https://github.com/nutanix/nunet-ui/issues/316
Resolves #https://github.com/nutanix/nunet-ui/issues/313
Resolves #https://github.com/nutanix/nunet-ui/issues/312
> s2s keys CRUD in provider API with authz

- papiea-client/src/entity_client.ts
> Add filter capability to client 

- papiea-client/package-lock.json
- papiea-client/package.json
- papiea-client/src/entity_client.ts
- papiea-core/package-lock.json
- papiea-core/package.json
- papiea-core/src/core.ts
- papiea-engine/docker-compose.yml
- papiea-engine/package-lock.json
- papiea-engine/package.json
- papiea-sdk/package-lock.json
- papiea-sdk/package.json
> Refactor entity types in client

- papiea-engine/__tests__/provider_api_auth.test.ts
- papiea-engine/src/auth/authn.ts
- papiea-engine/src/auth/authz.ts
- papiea-engine/src/provider/provider_api_impl.ts
- papiea-engine/src/provider/provider_api_interface.ts
- papiea-engine/src/provider/provider_routes.ts
Part of #https://github.com/nutanix/clusters/issues/254
> Provider-admin role added

- papiea-client/package-lock.json
- papiea-client/package.json
- papiea-client/src/entity_client.ts
- papiea-core/package-lock.json
- papiea-core/package.json
- papiea-engine/package-lock.json
- papiea-engine/package.json
- papiea-engine/src/entity/entity_api_impl.ts
- papiea-sdk/package-lock.json
- papiea-sdk/package.json
- papiea-sdk/src/provider_sdk/typescript_sdk.ts
- papiea-sdk/src/provider_sdk/typescript_sdk_context_impl.ts
> Add s2skey to ProceduralCtx

- papiea-client/package-lock.json
- papiea-client/package.json
- papiea-client/src/entity_client.ts
- papiea-core/package-lock.json
- papiea-core/package.json
- papiea-engine/package-lock.json
- papiea-engine/package.json
- papiea-engine/src/auth/authz.ts
- papiea-sdk/package-lock.json
- papiea-sdk/package.json
> Added apis to invoke all three kinds of procedures

- papiea-client/package-lock.json
- papiea-client/package.json
- papiea-core/package-lock.json
- papiea-core/package.json
- papiea-engine/__tests__/provider_sdk.test.ts
- papiea-engine/package-lock.json
- papiea-engine/package.json
- papiea-sdk/package-lock.json
- papiea-sdk/package.json
- papiea-sdk/src/provider_sdk/typescript_sdk.ts
> Remove spec dependency from entity procedure result

- .gitignore
- papiea-client/package-lock.json
- papiea-client/package.json
- papiea-core/package-lock.json
- papiea-core/package.json
- papiea-engine/package-lock.json
- papiea-engine/package.json
- papiea-engine/src/entity/entity_api_impl.ts
- papiea-sdk/package-lock.json
- papiea-sdk/package.json
> Add status to entity information of entity procedure

- papiea-engine/__tests__/api_docs.test.ts
- papiea-engine/__tests__/entity_api.test.ts
- papiea-engine/__tests__/location_kind_test_data.yml
- papiea-engine/__tests__/test_data_factory.ts
- papiea-engine/__tests__/validation.test.ts
- papiea-engine/src/main.ts
- papiea-engine/src/validator/index.ts
- papiea-sdk/src/provider_sdk/typescript_sdk.ts
- papiea-sdk/src/provider_sdk/typescript_sdk_validation.ts
> Validation Disallows extra props

- papiea-engine/src/entity/entity_api_impl.ts
- papiea-engine/src/entity/entity_api_interface.ts
- papiea-engine/src/entity/entity_routes.ts
resolves https://github.com/nutanix/nunet-ui/issues/314
> Add metadata extension on spec update

- papiea-engine/src/auth/oauth2.ts
resolves https://github.com/nutanix/nunet-ui/issues/286
> Add logout url

- papiea-engine/src/api_docs/api_docs_generator.ts
> Api docs auth

- papiea-engine/__tests__/procedures_api.test.ts
- papiea-engine/__tests__/provider_sdk.test.ts
- papiea-engine/src/entity/entity_api_impl.ts
- papiea-engine/src/validator/index.ts
- papiea-sdk/src/provider_sdk/typescript_sdk.ts
- papiea-sdk/src/provider_sdk/typescript_sdk_exceptions.ts
- papiea-sdk/src/provider_sdk/typescript_sdk_validation.ts
> Fixed validation & added procedure exceptions

- papiea-engine/src/auth/oauth2.ts
> Fix redirect uri endpoint to be exact

- papiea-engine/__tests__/entity_api.test.ts
- papiea-engine/src/api_docs/api_docs_generator.ts
- papiea-engine/src/entity/entity_routes.ts
- papiea-engine/src/utils/utils.ts
> Implemented pagination & tests for it

- papiea-client/package-lock.json
- papiea-client/package.json
- papiea-core/package-lock.json
- papiea-core/package.json
- papiea-engine/package-lock.json
- papiea-engine/package.json
- papiea-sdk/package-lock.json
- papiea-sdk/package.json
- papiea-sdk/src/provider_sdk/typescript_sdk.ts
- papiea-sdk/src/provider_sdk/typescript_sdk_context_impl.ts
- papiea-sdk/src/provider_sdk/typescript_sdk_interface.ts
closes https://github.com/nutanix/papiea-js/issues/223
> Add items to context

- papiea-engine/__tests__/entity_api.test.ts
- papiea-engine/src/databases/spec_db_interface.ts
- papiea-engine/src/databases/spec_db_mongo.ts
- papiea-engine/src/databases/status_db_interface.ts
- papiea-engine/src/databases/status_db_mongo.ts
- papiea-engine/src/entity/entity_api_impl.ts
- papiea-engine/src/entity/entity_api_interface.ts
- papiea-engine/src/entity/entity_routes.ts
- papiea-engine/src/utils/utils.ts
> Added sorting to filter endpoint

- papiea-engine/__tests__/entity_api_auth.test.ts
- papiea-engine/src/entity/entity_api_impl.ts
> Procedure should receive headers

- papiea-core/src/core.ts
- papiea-engine/__tests__/casbin_authorizer.test.ts
- papiea-engine/__tests__/entity_api.test.ts
- papiea-engine/__tests__/provider_sdk.test.ts
- papiea-engine/__tests__/test_data_factory.ts
- papiea-engine/src/auth/authn.ts
- papiea-engine/src/auth/authz.ts
- papiea-engine/src/auth/casbin.ts
- papiea-engine/src/entity/entity_api_impl.ts
- papiea-engine/src/entity/entity_api_interface.ts
- papiea-engine/src/entity/entity_routes.ts
- papiea-engine/src/provider/provider_api_impl.ts
- papiea-sdk/src/provider_sdk/typescript_sdk.ts
- papiea-sdk/src/provider_sdk/typescript_sdk_context_impl.ts
- papiea-sdk/src/provider_sdk/typescript_sdk_interface.ts
- papiea-sdk/src/provider_sdk/typescript_sdk_utils.ts
> Procedures check security

- papiea-engine/__tests__/entity_tests/entity_api.test.ts
- papiea-engine/src/entity/entity_routes.ts
- papiea-engine/src/provider/provider_routes.ts
- papiea-engine/src/validator/express_validator.ts
> Filter check input params

- papiea-engine/src/databases/mongo.ts
- papiea-engine/src/entity/entity_routes.ts
- papiea-engine/src/main.ts
- papiea-engine/src/validator/express_validator.ts
Related to #https://github.com/nutanix/nunet-ui/issues/443
See https://docs.aws.amazon.com/documentdb/latest/developerguide/security.encryption.ssl.html
> Support mongodb connection to AWS DocumentDB

- papiea-core/src/core.ts
- papiea-engine/src/auth/authn.ts
- papiea-engine/src/auth/s2s.ts
- papiea-engine/src/auth/session_key.ts
- papiea-engine/src/databases/s2skey_db_interface.ts
- papiea-engine/src/databases/s2skey_db_mongo.ts
- papiea-engine/src/databases/session_key_db_interface.ts
- papiea-engine/src/databases/session_key_db_mongo.ts
- papiea-engine/src/provider/provider_api_impl.ts
- papiea-engine/src/provider/provider_api_interface.ts
- papiea-engine/src/provider/provider_routes.ts
- papiea-sdk/src/provider_sdk/typescript_sdk.ts
- papiea-sdk/src/provider_sdk/typescript_sdk_context_impl.ts
- papiea-sdk/src/provider_sdk/typescript_sdk_interface.ts
resolves #242 
related to #245
> Changed secret to be aliased

- papiea-engine/__tests__/auth_tests/provider_api_auth.test.ts
- papiea-engine/src/auth/authz.ts
- papiea-engine/src/entity/entity_api_impl.ts
- papiea-engine/src/main.ts
- papiea-engine/src/provider/provider_api_impl.ts
- papiea-engine/src/provider/provider_api_interface.ts
> Fix read provider security using direct DB access

- README.md
- papiea-engine/src/main.ts
- papiea-engine/start.sh
The error path for Papiea-Engine does not log the error before returning. Adding that.
Resolved #272
> Router error logging

- .gitignore
- papiea-engine/src/databases/mongo.ts
> Add predownloaded cert

- papiea-client/package.json
- papiea-core/package.json
- papiea-engine/__tests__/sdk_tests/provider_sdk.test.ts
- papiea-engine/package.json
- papiea-engine/src/entity/entity_api_impl.ts
- papiea-engine/src/errors/procedure_invocation_error.ts
- papiea-engine/src/provider/provider_routes.ts
- papiea-engine/src/utils/utils.ts
- papiea-sdk/package.json
- papiea-sdk/src/provider_sdk/typescript_sdk.ts
- papiea-sdk/src/provider_sdk/typescript_sdk_exceptions.ts
> Fix provider error message propagation

- papiea-sdk/src/provider_sdk/typescript_sdk_logging.ts
> Added utc timestamp to sdk

- papiea-sdk/src/provider_sdk/typescript_sdk.ts
- papiea-sdk/src/provider_sdk/typescript_sdk_exceptions.ts
> Fixed SDK error status code propagation 

- papiea-engine/__tests__/sdk_tests/provider_sdk.test.ts
- papiea-engine/src/errors/on_action_error.ts
- papiea-engine/src/errors/papiea_error_impl.ts
- papiea-engine/src/intentful_core/intentful_strategy_interface.ts
> On_(create|delete) Improved error propagation & error messages

- papiea-engine/__tests__/sdk_tests/provider_sdk.test.ts
- papiea-sdk/src/provider_sdk/typescript_sdk_context_impl.ts
- papiea-sdk/src/provider_sdk/typescript_sdk_interface.ts
> Added ability to specify token & added tests

- papiea-engine/__tests__/sdk_tests/provider_sdk.test.ts
- papiea-sdk/src/provider_sdk/typescript_sdk.ts
> Removed unnecessary params from on_create|delete

- papiea-engine/__tests__/procedure_tests/procedures_api.test.ts
- papiea-engine/__tests__/sdk_tests/provider_sdk.test.ts
- papiea-engine/src/entity/entity_api_impl.ts
- papiea-engine/src/errors/procedure_invocation_error.ts
> Procedure validation failure returns 500 error to the end user instead of 400

- papiea-engine/src/intentful_core/intentful_strategy_interface.ts
- papiea-sdk/src/provider_sdk/typescript_sdk.ts
> Changed on create|delete semantics, added log messages

- papiea-engine/__benchmarks__/src/intentful_operations/intentful.ts
- papiea-engine/__benchmarks__/src/main.ts
- papiea-engine/__benchmarks__/src/test_data.ts
- papiea-engine/src/diff_resolver_main.ts
- papiea-engine/src/tasks/intentful_listener_mongo_stream.ts
- papiea-engine/src/tasks/task_resolver.ts
> Fixed a race condition by introducing regular task status update

- papiea-engine/src/provider/provider_api_impl.ts
- papiea-sdk/__tests__/sdk_tests/provider_sdk.test.ts
> Update status validation

- papiea-backend-utils/src/logging.ts
- papiea-engine/__tests__/auth_tests/provider_api_auth.test.ts
- papiea-engine/__tests__/provider_tests/provider_api.test.ts
- papiea-engine/package-lock.json
- papiea-engine/src/auth/authn.ts
- papiea-engine/src/provider/provider_api_impl.ts
- papiea-engine/src/provider/provider_api_interface.ts
- papiea-engine/src/provider/provider_routes.ts
- papiea-sdk/__tests__/intentful_workflow_tests/intentful_workflow.test.ts
- papiea-sdk/src/provider_sdk/typescript_sdk_context_impl.ts
> Fixed update status endpoint to include prefix & version

- papiea-engine/__tests__/task_tests/intentful_task.test.ts
- papiea-engine/src/audit_logging.ts
- papiea-engine/src/intentful_core/intentful_strategies/differ_intentful_strategy.ts
- papiea-sdk/__tests__/intentful_workflow_tests/intentful_workflow.test.ts
- papiea-sdk/src/provider_sdk/typescript_sdk.ts
> Changed the status creation logic for differ entities

- papiea-engine/__tests__/intentful_engine_tests/differ.test.ts
- papiea-engine/__tests__/intentful_engine_tests/sfs.test.ts
- papiea-engine/__tests__/intentful_engine_tests/sfs_compiler.test.ts
- papiea-engine/papiea-lib-clj/src/papiea-lib-clj/core.cljs
- papiea-engine/src/intentful_core/differ_impl.ts
- papiea-engine/src/intentful_core/sfs_compiler.ts
- papiea-engine/src/provider/provider_api_impl.ts
- papiea-engine/src/provider/provider_api_interface.ts
- papiea-sdk/__tests__/intentful_workflow_tests/intentful_workflow.test.ts
> Added sfs register-time checks and explanations

- papiea-engine/__tests__/validation_tests/validation.test.ts
resolves #394 
depends on https://github.com/swagger-model-validator/swagger-model-validator/issues/137 to be resolved
> [WIP] Validator string required regression test + fix

- papiea-engine/src/databases/status_db_mongo.ts
- papiea-engine/src/databases/watchlist_db_mongo.ts
- papiea-engine/src/errors/papiea_error_impl.ts
- papiea-engine/src/main.ts
- papiea-python-sdk/papiea/api.py
- papiea-python-sdk/papiea/client.py
- papiea-python-sdk/papiea/python_sdk.py
- papiea-python-sdk/papiea/python_sdk_context.py
> Fix Python SDK problems

- papiea-engine/__tests__/provider_tests/provider_api.test.ts
- papiea-engine/src/databases/provider_db_mongo.ts
> Reregister provider feature

- papiea-engine/__tests__/provider_tests/provider_api.test.ts
> Added reregister test to check that provider has changed

- papiea-engine/yarn.lock
- papiea-python-sdk/papiea/python_sdk_context.py
- papiea-sdk/__tests__/sdk_tests/provider_sdk.test.ts
- papiea-sdk/__tests__/test_data/location_kind_test_data_array.yml
- papiea-sdk/src/provider_sdk/typescript_sdk_context_impl.ts
- papiea-sdk/src/provider_sdk/typescript_sdk_interface.ts
> Replace status done & tested, PATCH update_status has some issues

- papiea-engine/src/tasks/diff_resolver.ts
- papiea-sdk/__tests__/intentful_workflow_tests/intentful_workflow.test.ts
- papiea-sdk/src/provider_sdk/typescript_sdk.ts
> fix and test for delay time

- papiea-backend-utils/src/dotnotation.ts
- papiea-backend-utils/src/index.ts
- papiea-engine/package.json
- papiea-engine/src/databases/spec_db_mongo.ts
- papiea-engine/src/databases/status_db_mongo.ts
- papiea-engine/src/databases/utils/filtering.ts
- papiea-engine/yarn.lock
Add dotnotation which skips vectors
Fixes #415
> Fix update_status to have vector-replace semantics

- papiea-core/src/core.ts
- papiea-python-sdk/papiea/api.py
- papiea-python-sdk/papiea/core.py
- papiea-python-sdk/papiea/python_sdk.py
- papiea-python-sdk/papiea/python_sdk_context.py
- papiea-python-sdk/papiea/python_sdk_exceptions.py
- papiea-python-sdk/papiea/utils.py
resolves #409 
resolves #404 
resolves #402
> Specific Python-SDK papiea errors

- papiea-client/__tests__/filter.test.ts
- papiea-client/jest.config.js
- papiea-client/package.json
- papiea-client/src/entity_client.ts
- papiea-client/src/location_client_example.ts
- papiea-client/yarn.lock
- papiea-sdk/python/papiea/client.py
- papiea-sdk/typescript/jest.config.js
> Filter & List Papiea-Client generator implementation

- papiea-sdk/python/papiea/python_sdk.py
> Fixed papiea SDK bugs

- papiea-core/src/core.ts
- papiea-engine/__tests__/database_tests/database_mongo.test.ts
- papiea-engine/src/api_docs/api_docs_generator.ts
- papiea-engine/src/databases/spec_db_mongo.ts
- papiea-engine/src/databases/status_db_interface.ts
- papiea-engine/src/databases/status_db_mongo.ts
- papiea-engine/src/entity/entity_api_impl.ts
- papiea-engine/src/entity/entity_api_interface.ts
- papiea-engine/src/entity/entity_routes.ts
- papiea-engine/src/intentful_core/intentful_strategies/status_update_strategy.ts
- papiea-engine/src/intentful_engine/diff_resolver.ts
- papiea-engine/src/intentful_engine/intent_resolver.ts
- papiea-engine/src/provider/provider_api_impl.ts
- papiea-sdk/typescript/__tests__/intentful_workflow_tests/intentful_workflow.test.ts
> Tests shared UUID watchlist

- Makefile
- papiea-core/src/core.ts
- papiea-engine/__tests__/database_tests/database_mongo.test.ts
- papiea-engine/src/api_docs/api_docs_generator.ts
- papiea-engine/src/api_docs/api_docs_routes.ts
- papiea-engine/src/databases/spec_db_mongo.ts
- papiea-engine/src/databases/status_db_interface.ts
- papiea-engine/src/databases/status_db_mongo.ts
- papiea-engine/src/entity/entity_api_impl.ts
- papiea-engine/src/entity/entity_api_interface.ts
- papiea-engine/src/entity/entity_routes.ts
- papiea-engine/src/intentful_core/intentful_strategies/differ_intentful_strategy.ts
- papiea-engine/src/intentful_core/intentful_strategies/status_update_strategy.ts
- papiea-engine/src/intentful_engine/diff_resolver.ts
- papiea-engine/src/intentful_engine/intent_resolver.ts
- papiea-engine/src/intentful_engine/intentful_listener_mongo_simple.ts
- papiea-engine/src/intentful_engine/intentful_listener_mongo_stream.ts
- papiea-engine/src/intentful_engine/watchlist.ts
- papiea-engine/src/provider/provider_api_impl.ts
- papiea-sdk/python/papiea/python_sdk.py
- papiea-sdk/typescript/__tests__/intentful_workflow_tests/intentful_workflow.test.ts
There are a few critical fixes in here needed to get BMaaS and Griffon working together; please see the individual commit messages for more details.
> Watchlist and Python fixes

- papiea-engine/__tests__/provider_tests/provider_api.test.ts
- papiea-engine/__tests__/test_data/cluster_kind_with_nullable_fields_test_data.yml
- papiea-engine/__tests__/test_data_factory.ts
- papiea-engine/src/databases/status_db_mongo.ts
- papiea-engine/src/validator/index.ts
> Update status undefined & null values

- papiea-sdk/python/papiea/core.py
> Fixes to Python SDK problems

- papiea-engine/src/errors/on_action_error.ts
- papiea-engine/src/intentful_core/intentful_strategies/intentful_strategy_interface.ts
- papiea-sdk/typescript/__tests__/sdk_tests/provider_sdk.test.ts
- papiea-sdk/typescript/src/provider_sdk/typescript_sdk.ts
> Refactoring & changes to on_create|delete actions

- papiea-engine/__tests__/database_tests/database_mongo.test.ts
- papiea-engine/__tests__/entity_tests/entity_api.test.ts
- papiea-engine/src/databases/graveyard_db_interface.ts
- papiea-engine/src/databases/graveyard_db_mongo.ts
- papiea-engine/src/databases/mongo.ts
- papiea-engine/src/databases/spec_db_interface.ts
- papiea-engine/src/databases/spec_db_mongo.ts
- papiea-engine/src/databases/status_db_interface.ts
- papiea-engine/src/databases/status_db_mongo.ts
- papiea-engine/src/diff_resolver_main.ts
- papiea-engine/src/entity/entity_api_impl.ts
- papiea-engine/src/entity/entity_api_interface.ts
- papiea-engine/src/entity/entity_routes.ts
- papiea-engine/src/intentful_core/intentful_context.ts
- papiea-engine/src/intentful_core/intentful_strategies/basic_intentful_strategy.ts
- papiea-engine/src/intentful_core/intentful_strategies/differ_intentful_strategy.ts
- papiea-engine/src/intentful_core/intentful_strategies/intentful_strategy_interface.ts
- papiea-engine/src/intentful_core/intentful_strategies/spec_only_intentful_strategy.ts
- papiea-engine/src/main.ts
- papiea-sdk/typescript/src/provider_sdk/typescript_sdk.ts
> Added graveyard & changes

- papiea-engine/__tests__/entity_tests/entity_api.test.ts
- papiea-engine/src/databases/graveyard_db_interface.ts
- papiea-engine/src/databases/graveyard_db_mongo.ts
- papiea-engine/src/databases/utils/errors.ts
- papiea-engine/src/entity/entity_api_impl.ts
- papiea-engine/src/entity/entity_routes.ts
- papiea-engine/src/errors/papiea_error_impl.ts
- papiea-engine/src/intentful_core/intentful_strategies/intentful_strategy_interface.ts
> Spec version range in graveyard implemented

- papiea-engine/src/intentful_core/intentful_strategies/intentful_strategy_interface.ts
- papiea-sdk/typescript/__tests__/sdk_tests/provider_sdk.test.ts
> Fix constructor running twice bug

- papiea-engine/src/intentful_core/intentful_strategies/intentful_strategy_interface.ts
- papiea-sdk/typescript/__tests__/sdk_tests/provider_sdk.test.ts
> Fixed constructor problem & added test

- papiea-engine/__tests__/provider_tests/provider_api.test.ts
- papiea-engine/__tests__/test_data/cluster_kind_test_data.yml
- papiea-engine/__tests__/test_data/location_kind_test_data_array.yml
- papiea-engine/__tests__/test_data_factory.ts
- papiea-engine/src/provider/provider_api_impl.ts
> Improvements and fixes to Status validation portion

- .circleci/Dockerfile
- papiea-engine/__tests__/docs_tests/api_docs.test.ts
- papiea-engine/__tests__/test_data/location_kind_test_data_basic.yml
- papiea-engine/__tests__/test_data_factory.ts
- papiea-engine/__tests__/validation_tests/validation.test.ts
> Fix status-only on spec-only entity in test data

- upgrade-versions.sh
handle multiple grep matches of the pattern, fix type of the typescript version variable
> Add changelog fix

- papiea-engine/__tests__/database_tests/database_mongo.test.ts
- papiea-engine/src/diff_resolver_main.ts
- papiea-engine/src/intentful_engine/diff_resolver.ts
- papiea-engine/src/intentful_engine/intent_interface.ts
- papiea-engine/src/intentful_engine/watchlist.ts
- papiea-engine/src/utils/utils.ts
- papiea-sdk/typescript/__tests__/intentful_workflow_tests/intentful_workflow.test.ts
> Exponential backoff implementation

- papiea-engine/__tests__/entity_tests/extension.test.ts
- papiea-engine/src/validator/index.ts
> Fixed multiple validation problems

- README.md
- papiea-engine/src/diff_resolver_main.ts
- papiea-engine/src/utils/arg_parser.ts
> Add new options to customize timeouts

- papiea-engine/__tests__/docs_tests/api_docs.test.ts
- papiea-engine/src/api_docs/api_docs_generator.ts
> Fixed spec incorrect for two different kinds with same procedure name

- papiea-engine/src/validator/index.ts
- papiea-sdk/typescript/__tests__/sdk_tests/provider_sdk.test.ts
> Fixed validator error connected to optional fields

- .github/ISSUE_TEMPLATE/bug_report.md
- README.md
> Provide a sample bug report instruction

- CHANGELOG.md
- README.md
- papiea-backend-utils/package.json
- papiea-client/package.json
- papiea-core/package.json
- papiea-engine/package.json
- papiea-engine/src/errors/procedure_invocation_error.ts
- papiea-sdk/python/e2e_tests/requirements.txt
- papiea-sdk/typescript/package.json
Modified error fields initialization within the procedure invocation error type to limit redundant error fields
> Limit error values in procedure invocation error

- papiea-engine/src/intentful_engine/intent_resolver.ts
- papiea-sdk/typescript/__tests__/intentful_workflow_tests/intentful_workflow.test.ts
> Fix partial array update error

- papiea-core/src/core.ts
- papiea-engine/__tests__/database_tests/database_mongo.test.ts
- papiea-engine/src/databases/graveyard_db_mongo.ts
- papiea-engine/src/databases/spec_db_interface.ts
- papiea-engine/src/databases/spec_db_mongo.ts
- papiea-engine/src/entity/entity_api_impl.ts
- papiea-engine/src/entity/entity_api_interface.ts
- papiea-engine/src/entity/entity_routes.ts
- papiea-engine/src/intentful_core/intentful_strategies/differ_intentful_strategy.ts
- papiea-engine/src/intentful_engine/diff_resolver.ts
- papiea-engine/src/intentful_engine/intent_resolver.ts
- papiea-engine/src/intentful_engine/watchlist.ts
- papiea-sdk/typescript/__tests__/intentful_workflow_tests/intentful_workflow.test.ts
- papiea-sdk/typescript/__tests__/sdk_tests/provider_sdk.test.ts
- papiea-sdk/typescript/src/provider_sdk/typescript_sdk_context_impl.ts
- papiea-sdk/typescript/src/provider_sdk/typescript_sdk_interface.ts
> Fix status not found deletion bug

- papiea-engine/__tests__/docs_tests/api_docs.test.ts
- papiea-engine/__tests__/test_data/customschema_swagger.json
- papiea-engine/src/api_docs/admin_swagger.json
Fix errors related to the admin swagger and other errors within the api-docs code related to swagger
> Fix swagger errors in papiea-engine

- papiea-engine/src/validator/express_validator.ts
- Modified the error message thrown by validator due to missing body/query params in procedure request.
> Changed error message for bad request error in validator

- papiea-engine/package.json
- papiea-sdk/typescript/package.json
> Fix .toLowerCase() validation bug

- papiea-backend-utils/src/dotnotation.ts
- papiea-engine/__tests__/provider_tests/provider_api.test.ts
- papiea-engine/src/databases/status_db_mongo.ts
- papiea-engine/src/provider/provider_api_impl.ts
- papiea-engine/src/provider/provider_api_interface.ts
- Separated null valued fields and unset them in status db update.
- Removed fix null objects module which replaced null value with `{}`.
> Separated null value fields and unset in status db

- README.md
- papiea-backend-utils/src/index.ts
- papiea-backend-utils/src/logging.ts
- papiea-engine/src/audit_logging.ts
- papiea-engine/src/diff_resolver_main.ts
- papiea-engine/src/main.ts
- papiea-engine/src/utils/arg_parser.ts
> Logging verbosity

- papiea-engine/src/intentful_core/entity_creation_strategies/basic_entity_creation_strategy.ts
- papiea-sdk/typescript/__tests__/sdk_tests/provider_sdk.test.ts
> Added check for the wrong format when constructor is not present

- papiea-engine/src/auth/authz.ts
- papiea-engine/src/diff_resolver_main.ts
- papiea-engine/src/entity/entity_api_impl.ts
- papiea-engine/src/intentful_core/intentful_context.ts
- papiea-engine/src/intentful_core/intentful_strategies/differ_intentful_strategy.ts
- papiea-engine/src/main.ts
- papiea-sdk/typescript/__tests__/sdk_tests/provider_sdk.test.ts
- Added intent watcher authorizor implementation for watcher related ops.
- Added tests to verify the authorization for intent watcher related ops.
> Added authorizer for intent watcher related operations

- papiea-engine/src/diff_resolver_main.ts
- papiea-engine/src/errors/papiea_error_impl.ts
- papiea-engine/src/intentful_core/entity_creation_strategies/constructor_entity_creation_strategy.ts
- papiea-engine/src/main.ts
- papiea-engine/src/utils/utils.ts
- papiea-sdk/typescript/__tests__/sdk_tests/provider_sdk.test.ts
> Logging to errors and unauthorized to constructor

- papiea-engine/src/validator/index.ts
- papiea-sdk/typescript/__tests__/sdk_tests/provider_sdk.test.ts
Closes #601 
- Added value checks in validate_status_only_field function to avoid undefined value access in validator.
- Added test to verify the validator module.
> Added strict checking in validate status-only fields module in validator

- papiea-backend-utils/src/tracing.ts
- papiea-client/src/entity_client.ts
- papiea-sdk/typescript/__tests__/sdk_tests/provider_sdk.test.ts
> Fix client tracing issues

- README.md
- papiea-backend-utils/src/tracing.ts
- papiea-engine/src/main.ts
- papiea-engine/src/utils/arg_parser.ts
- papiea-engine/src/utils/arg_parser_schemas.ts
resolves @joshua-berry-ntnx ask to reduce jaeger error noise
> Jaeger suppress messages config

- .circleci/config.yml
- .circleci/docker-compose.yml
- CHANGELOG.md
- README.md
- papiea-backend-utils/package.json
- papiea-client/package.json
- papiea-core/package.json
- papiea-engine/package.json
- papiea-engine/publish-images-release.py
- papiea-engine/publish-images.py
- papiea-engine/src/validator/express_validator.ts
- papiea-sdk/typescript/package.json
> Optimize CI time

- papiea-core/src/core.ts
- papiea-engine/__tests__/intentful_engine_tests/differ.test.ts
- papiea-engine/__tests__/intentful_engine_tests/sfs_compiler.test.ts
- papiea-engine/src/intentful_core/differ_impl.ts
- papiea-engine/src/intentful_core/sfs_compiler.ts
- papiea-engine/src/intentful_engine/diff_resolver.ts
- papiea-engine/src/intentful_engine/intent_resolver.ts
- papiea-sdk/typescript/__tests__/sdk_tests/provider_sdk.test.ts
Closes #644
- Added helper function to remove undefined fields from status and spec passed to differ input.
- Added tests to verify the changes.
> Remove undefined and null fields from the differ input

- papiea-sdk/python/papiea/python_sdk.py
- papiea-sdk/typescript/__tests__/intentful_workflow_tests/intentful_workflow.test.ts
- papiea-sdk/typescript/src/provider_sdk/typescript_sdk.ts
> Background task implementation

- papiea-engine/src/intentful_core/sfs_compiler.ts
Closes #644
- Modified logic for remove undefined/null values to avoid corner cases.
> Modified logic for the sanitizer functions in sfs compiler

- papiea-engine/__tests__/provider_tests/provider_api.test.ts
- papiea-engine/src/validator/index.ts
- papiea-sdk/typescript/src/provider_sdk/typescript_sdk.ts
> Remove nullable fields

- papiea-engine/src/validator/index.ts
- papiea-sdk/typescript/__tests__/sdk_tests/provider_sdk.test.ts
> Added validator check for untyped object not marked as status-only

- papiea-sdk/python/papiea/core.py
- papiea-sdk/python/papiea/python_sdk.py
> [Python] Fixed custom field and metadata extension bug for background task

- papiea-backend-utils/src/axios_response_parser.ts
- papiea-backend-utils/src/index.ts
- papiea-engine/__tests__/auth_tests/entity_api_auth.test.ts
- papiea-engine/__tests__/auth_tests/provider_api_auth.test.ts
- papiea-engine/__tests__/entity_tests/entity_api.test.ts
- papiea-engine/__tests__/entity_tests/extension.test.ts
- papiea-engine/__tests__/entity_tests/pagination.test.ts
- papiea-engine/__tests__/entity_tests/uuid_validation.test.ts
- papiea-engine/__tests__/procedure_tests/procedures_api.test.ts
- papiea-engine/__tests__/provider_tests/provider_api.test.ts
- papiea-sdk/typescript/__tests__/client_e2e_tests/entity_client.test.ts
- papiea-sdk/typescript/__tests__/intentful_workflow_tests/intentful_workflow.test.ts
- papiea-sdk/typescript/__tests__/sdk_tests/provider_sdk.test.ts
Closes #656
- Added helper modules in the axios response parser class.     
- Modified sdk and engine tests to use the axios response parser.
> Added axios response parser in the backend utils

- papiea-engine/src/main.ts
- papiea-sdk/typescript/src/provider_sdk/typescript_sdk.ts
Needed to get Papiea working with large entities in production.
> Emergency fix to allow larger HTTP request sizes

- papiea-engine/__tests__/database_tests/database_mongo.test.ts
- papiea-engine/src/databases/watchlist_db_interface.ts
- papiea-engine/src/databases/watchlist_db_mongo.ts
- papiea-engine/src/diff_resolver_main.ts
- papiea-engine/src/intentful_core/entity_creation_strategies/basic_entity_creation_strategy.ts
- papiea-engine/src/intentful_core/entity_creation_strategies/constructor_entity_creation_strategy.ts
- papiea-engine/src/intentful_core/intentful_strategies/differ_intentful_strategy.ts
- papiea-engine/src/intentful_core/intentful_strategies/status_update_strategy.ts
- papiea-engine/src/intentful_core/sfs_compiler.ts
- papiea-engine/src/intentful_engine/diff_resolver.ts
- papiea-engine/src/intentful_engine/intent_resolver.ts
- papiea-engine/src/intentful_engine/intentful_listener_mongo_simple.ts
- papiea-engine/src/intentful_engine/watchlist.ts
- papiea-engine/src/utils/utils.ts
- papiea-sdk/typescript/__tests__/intentful_workflow_tests/intentful_workflow.test.ts
Creating this PR since the background tasks related tests are not stable, @Ntnx-Igor-Korotach I need your help on that.
Also, wanted to get this reviewed once before we merge it in master.
> Race condition fixes in master

- papiea-engine/src/databases/watchlist_db_mongo.ts
- papiea-engine/src/intentful_core/intentful_strategies/differ_intentful_strategy.ts
- papiea-engine/src/intentful_engine/watchlist.ts
Closes #702 
- Added hash in watchlist db to detect conflicts.
- Added retry logic to update watchlist in case of conflict.
> Fixed race condition in watchlist updates

- papiea-engine/src/main.ts
- papiea-engine/src/utils/arg_parser.ts
- papiea-sdk/python/papiea/python_sdk.py
> Added flag to disable https in papiea engine

- papiea-backend-utils/package.json
- papiea-backend-utils/src/dotnotation.ts
- papiea-backend-utils/src/logging.ts
- papiea-backend-utils/yarn.lock
- papiea-client/yarn.lock
- papiea-engine/__benchmarks__/yarn.lock
- papiea-engine/src/auth/casbin.ts
- papiea-engine/src/main.ts
- papiea-engine/yarn.lock
- papiea-sdk/typescript/__tests__/client_e2e_tests/utils.ts
- papiea-sdk/typescript/src/provider_sdk/typescript_sdk.ts
- papiea-sdk/typescript/src/provider_sdk/typescript_sdk_context_impl.ts
- papiea-sdk/typescript/src/provider_sdk/typescript_sdk_interface.ts
- papiea-sdk/typescript/yarn.lock
> Changed the implementation of the logger from winston to pino
