__tests__/entity_api.test.ts, src/databases/spec_db_mongo.ts, src/databases/utils/errors.ts, src/main.ts
If we go with propagating internal server error a.k.a 500, we are leaking some info as well as not giving informative error
=> Added 404 instead of 500 error when no entity is found

__tests__/entity_api.test.ts, __tests__/provider_api.test.ts, package.json, src/entity/entity_api_impl.ts, src/entity/entity_api_interface.ts, src/entity/entity_routes.ts, src/main.ts, src/provider/provider_api_impl.ts, src/provider/provider_api_interface.ts, src/provider/provider_routes.ts
To keep interfaces more clean and increase cohesion moved validation to Entity and Provider API impl classes
=> Move validation from routes to API impl classes

papiea-engine/__tests__/provider_api_auth.test.ts, papiea-engine/src/auth/authz.ts, papiea-engine/src/provider/provider_api_impl.ts
Resolves #201
✓ Admin should create s2s key for provider-admin (49ms)
✓ Admin should create s2s key for provider-admin with key provided (10ms)
✓ Provider-admin should register and unregister provider (14ms)
✓ Provider-admin should not register provider with another prefix (7ms)
✓ Provider-admin should update status (35ms)
✓ Provider-admin should not update status for provider with another prefix (19ms)
✓ Provider-admin should not create s2s key for admin (7ms)
✓ Provider-admin should not create s2s key with another provider prefix (7ms)
✓ Provider-admin should create s2s key for another provider-admin (9ms)
✓ Provider-admin should create s2s key for provider-user (8ms)
✓ Provider-admin should not create s2s key for provider-user with provider-user owner (8ms)
✓ Provider-user should list …
=> Provider-admin rights refined

papiea-engine/__tests__/entity_api_auth.test.ts, papiea-engine/src/auth/authz.ts, papiea-engine/src/auth/casbin.ts
* If one uses a policy
`p, alice, owner, ${kind_name}, *, allow`
this means that owner of the entity may do all actions on top of it, including all procedure calls
* To be more explicit
```
p, alice, owner, ${kind_name}, read, allow
p, alice, owner, ${kind_name}, callmovex, allow
````
This allows alice to call moveX entity procedure for entities of which she is an owner, note that read permission is also required as entity will be read and given to the procedure
* auth for kind and provider level procedures does not work with current casbin model for provider-user because there is no owner or tenant on kind or provider level
* provider-admin can call all kind and provider procedures of his provider
=> Call procedure auth tests

papiea-engine/src/main.ts
because proxy may change the url like /papiea/api-docs
Resolves #196
=> Use relative url for api-docs

papiea-engine/__tests__/logging_tests/logger.test.ts, papiea-engine/src/logger.ts, papiea-engine/src/logger_interface.ts, papiea-engine/src/utils/utils.ts
resolves #294 
New logs in console look like the following:
```
{  
"0":{  
"two":"errors"
},
"1":{  
"three":"errors"
},
"2":{  
"Time":"2019-08-21T15:00:42.118Z"
},
"level":"error",
"message":{  
"one":"error"
}
}
```
=> Changed logger to be pretty printed & fixed a bug and added test

papiea-engine/package-lock.json, papiea-engine/src/auth/authn.ts
resolves #332 
`const adminKey = process.env.PAPIEA_ADMIN_S2S_KEY || '';`  wasn't working with function getToken(). 
`return req.headers.authorization.split(' ')[1] || '';` was returning `undefined` which is not expected by the function output
=> Default variable for PAPIEA_ADMIN_S2S_KEY wasn't working correctly

papiea-client/src/entity_client.ts, papiea-client/src/errors/errors.ts, papiea-core/src/core.ts, papiea-engine/src/errors/papiea_error_impl.ts, papiea-engine/src/main.ts
resolves #376 
It seems like we are still going for papiea-core package to be a DTO so I decided not to move errors there. Moreover, another reason is having flexibility in processing errors on papiea and on the client. Also exceptions should not be a contract, they should be a convenience, JSON structure of an error should be a contract
=> Added papiea errors to client

.circleci/Dockerfile
For some reason, `$home` does not point to where yarn is actually installed. Explicitly setting that up makes it work.
Now we have a different issue.
=> Installing yarn

papiea-engine/__tests__/database_tests/database_mongo.test.ts, papiea-engine/__tests__/entity_tests/entity_api.test.ts, papiea-engine/__tests__/entity_tests/filtering.test.ts, papiea-engine/src/databases/spec_db_interface.ts, papiea-engine/src/databases/spec_db_mongo.ts, papiea-engine/src/databases/status_db_interface.ts, papiea-engine/src/databases/status_db_mongo.ts, papiea-engine/src/databases/utils/filtering.ts, papiea-engine/src/entity/entity_api_impl.ts, papiea-engine/src/entity/entity_api_interface.ts, papiea-engine/src/entity/entity_routes.ts, papiea-engine/src/errors/procedure_invocation_error.ts, papiea-engine/src/utils/utils.ts
resolves #407 
Added `/filter?exact=true` to preserve original exact filtering capabilities. By default this is false and asides from field order issues, adds ability to filter not necessarily specifying all fields in spec/status. E.g.
```
{
"spec": {
"state": "free",
"type": {
"kind": "machine-type",
"uuid": "cb498080-715b-405e-8071-7e2398c2bf0f"
}
}
}
```
now also can be filtered by:
```
{
"spec": {
"type": {
"kind": "machine-type",
}
}
}
```
=> Fixed filtering problems & added tests

papiea-engine/src/intentful_core/intentful_strategies/differ_intentful_strategy.ts, papiea-sdk/typescript/__tests__/intentful_workflow_tests/intentful_workflow.test.ts
resolves #469 
@joshua-berry-ntnx I couldn't find the race condition described in the issue and added a few tests for concurrent and serial updates. A few words though:
1) `Differ` entities always return Watcher as a response to any PUT request (Failed one in case of CAS problem)
2) All the other entities return `409 Conflicting Entity` Error in case of CAS problem
Thus for `Differ` entities I added error message in case of CAS fail to signify what is the problem exactly.
=> Added tests & added error message in case of failed status watcher

papiea-engine/src/intentful_core/intentful_strategies/differ_intentful_strategy.ts, papiea-sdk/typescript/__tests__/intentful_workflow_tests/intentful_workflow.test.ts
@shlomi-nx now that all the entities throw, what is the use for `Failed` status on IntentWatcher? I've left it just in case we would like to have history of intent changes illustrated by watchers but still
=> Conflicting entities now always throw the exception

papiea-engine/__tests__/docs_tests/api_docs.test.ts, papiea-engine/__tests__/provider_tests/provider_api.test.ts, papiea-engine/__tests__/test_data_factory.ts, papiea-engine/__tests__/validation_tests/validation.test.ts, papiea-engine/src/api_docs/api_docs_generator.ts, papiea-engine/src/validator/index.ts, papiea-sdk/typescript/__tests__/test_data/location_kind_test_data.yml
resolves #468 
When a field is marked as 'status-only" it doesn't appear in required fields for spec anymore
=> issues-468: remove status-only fields from required sections of spec api

CHANGELOG.md, upgrade-versions.sh
issue #485 
appends message from the last commit when things are merged to master. (Assumed that the PR is squashed to 1 commit)
example of the addition to the CHANGELOG.md:
- Version 1.1: Upgrade version scripts and README version section (#479) PR url: https://github.com/nutanix/papiea/pull/479
=> introduce appending changes to CHANGELOG.md when PR is merged to master

papiea-engine/src/errors/procedure_invocation_error.ts, papiea-sdk/typescript/__tests__/sdk_tests/provider_sdk.test.ts
Added stacktrace and errors field for validation error in procedure invocation and test to verify the same.
So far, I've added additional information for the `validation error` within the `Procedure Invocation Error` and will look at other places as well to ensure proper value for fields in error type.
=> Add additional info in procedure invocation error

papiea-client/__tests__/filter.test.ts, papiea-client/__tests__/update.test.ts, papiea-core/src/core.ts, papiea-engine/src/intentful_core/differ_impl.ts, papiea-engine/src/intentful_engine/diff_resolver.ts, papiea-sdk/typescript/__tests__/sdk_tests/provider_sdk.test.ts, papiea-sdk/typescript/src/provider_sdk/typescript_sdk_exceptions.ts
Added module to loop through the entity schema and remove all the `status-only` fields from the entity status object.
Added test to verify the functionality
=> Added module to remove status-only fields from entity status

papiea-backend-utils/src/logging.ts, papiea-engine/src/databases/status_db_mongo.ts, papiea-sdk/python/e2e_tests/procedure_handlers.py, papiea-sdk/python/e2e_tests/requirements.txt, papiea-sdk/python/papiea/python_sdk_context.py, papiea-sdk/typescript/__tests__/sdk_tests/provider_sdk.test.ts, papiea-sdk/typescript/src/provider_sdk/typescript_sdk_context_impl.ts
- Added info about the function and deprecate tag for the replace_status sdk method.
- Added tests to verify the update_status method and ensure similarity to replace_status.
- Modified mongo update_status method to use upsert flag for update call.
=> Added deprecate info for the replace_status sdk method and relavant tests

papiea-engine/src/validator/index.ts, papiea-sdk/python/e2e_tests/procedure_handlers.py, papiea-sdk/typescript/__tests__/sdk_tests/provider_sdk.test.ts
- Added validation function to throw error if a required `status-only` field exists in schema.
- Added validation function to throw error is create/update spec contains value for a `status-only` field.
- Added tests to verify the above validation functions.
=> Added validation check to not allow required status-only fields in schema

papiea-client/__tests__/filter.test.ts, papiea-client/__tests__/update.test.ts, papiea-client/src/entity_client.ts, papiea-engine/src/main.ts, papiea-engine/src/utils/utils.ts, papiea-engine/src/validator/express_validator.ts, papiea-sdk/typescript/__tests__/sdk_tests/provider_sdk.test.ts, papiea-sdk/typescript/src/provider_sdk/typescript_sdk.ts, papiea-sdk/typescript/src/provider_sdk/typescript_sdk_utils.ts
- Added get version function in the typescript provider sdk class,
- Defined version header to use in the papiea sdk requests.
- Defined a version check middleware in express validator to validate the sdk version.
=> Added semantic version check for the papiea sdk requests

papiea-sdk/python/papiea/python_sdk.py, papiea-sdk/typescript/__tests__/sdk_tests/provider_sdk.test.ts, papiea-sdk/typescript/src/provider_sdk/typescript_sdk.ts
Closes #605 
- Changed input schema to optional parameter and use kind structure if it is undefined.
- Added test to verify the use of kind structure when input schema is undefined.
=> Use kind structure in on_create if input schema is missing

papiea-engine/__tests__/docs_tests/api_docs.test.ts, papiea-engine/__tests__/test_data_factory.ts, papiea-engine/src/api_docs/api_docs_generator.ts
Closes #603
- Removed misleading input field tag from the constructor procedure schema function.
- Added WithEntityConstructor function to allow on_create handler in test data factory.
=> Removed input tag from the constructor procedure schema in api docs

papiea-backend-utils/src/logging.ts, papiea-engine/papiea-config.yaml, papiea-engine/src/diff_resolver_main.ts, papiea-engine/src/main.ts, papiea-engine/src/utils/arg_parser.ts, papiea-sdk/typescript/__tests__/client_e2e_tests/utils.ts, papiea-sdk/typescript/__tests__/sdk_tests/provider_sdk.test.ts, papiea-sdk/typescript/src/provider_sdk/typescript_sdk.ts, papiea-sdk/typescript/src/provider_sdk/typescript_sdk_context_impl.ts
Closes #640
- Added support for pretty print config variable.
- Modified LoggerOptions to use pretty print flag to replace the format variable.
- Set pretty print to true for papiea use.
=> Removed dependency on Node env production variable in printing logs

papiea-engine/src/intentful_core/intentful_strategies/intentful_strategy_interface.ts, papiea-engine/src/intentful_core/sfs_compiler.ts, papiea-sdk/typescript/__tests__/sdk_tests/provider_sdk.test.ts, papiea-sdk/typescript/src/provider_sdk/typescript_sdk.ts
Closes #675
- Fixed deep copy bug in differ sanitizer functions
- Modified destructor handler input to include the complete entity structure.
=> Pass recent entity info to destructors/intent handlers

papiea-engine/Dockerfile, papiea-engine/__tests__/database_tests/database_mongo.test.ts, papiea-engine/__tests__/entity_tests/sorting.test.ts, papiea-engine/src/auth/authz.ts, papiea-engine/src/databases/intent_watcher_db_interface.ts, papiea-engine/src/databases/intent_watcher_db_mongo.ts, papiea-engine/src/entity/entity_api_impl.ts, papiea-engine/src/entity/entity_api_interface.ts, papiea-engine/src/entity/entity_routes.ts, papiea-engine/src/intentful_engine/intent_interface.ts, papiea-engine/src/intentful_engine/intent_resolver.ts, papiea-engine/src/provider/provider_api_impl.ts, papiea-engine/src/utils/async.ts
If we have accumulated a lot of intent watchers in the DB due to spec changes,
they may not all fit in memory. Indeed, we have seen OOM issues in production
because of this.
We also saw another OOM issue due to a complete lack of flow control in the
intent_resolver—if we have too many intent watchers to update, the process of
updating them all may take so long that we start the next round, and
progressively run more and more updates in parallel until we run out of memory.
Makes some progress on #679.
=> Fix OOM issue && Use AsyncIterators to fetch intent watchers
